/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserApplicationsRouteImport } from './routes/user-applications'
import { Route as UserRouteImport } from './routes/user'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccidentsRouteImport } from './routes/accidents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatisticsIndexRouteImport } from './routes/statistics/index'
import { Route as UserFormRouteImport } from './routes/user_.form'
import { Route as StatisticsStreetsRouteImport } from './routes/statistics/streets'
import { Route as StatisticsPreviousQuarterRouteImport } from './routes/statistics/previous-quarter'
import { Route as StatisticsMainRouteImport } from './routes/statistics/main'
import { Route as RegisterPoliceRouteImport } from './routes/register_.police'
import { Route as RegisterMedicRouteImport } from './routes/register_.medic'
import { Route as PersonsPersonIdRouteImport } from './routes/persons.$personId'
import { Route as AccidentsNewRouteImport } from './routes/accidents_/new'
import { Route as AccidentsNewVehicleRouteImport } from './routes/accidents_/new/vehicle'
import { Route as AccidentsNewPersonRouteImport } from './routes/accidents_/new/person'

const UserApplicationsRoute = UserApplicationsRouteImport.update({
  id: '/user-applications',
  path: '/user-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccidentsRoute = AccidentsRouteImport.update({
  id: '/accidents',
  path: '/accidents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsIndexRoute = StatisticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StatisticsRoute,
} as any)
const UserFormRoute = UserFormRouteImport.update({
  id: '/user_/form',
  path: '/user/form',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsStreetsRoute = StatisticsStreetsRouteImport.update({
  id: '/streets',
  path: '/streets',
  getParentRoute: () => StatisticsRoute,
} as any)
const StatisticsPreviousQuarterRoute =
  StatisticsPreviousQuarterRouteImport.update({
    id: '/previous-quarter',
    path: '/previous-quarter',
    getParentRoute: () => StatisticsRoute,
  } as any)
const StatisticsMainRoute = StatisticsMainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => StatisticsRoute,
} as any)
const RegisterPoliceRoute = RegisterPoliceRouteImport.update({
  id: '/register_/police',
  path: '/register/police',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterMedicRoute = RegisterMedicRouteImport.update({
  id: '/register_/medic',
  path: '/register/medic',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsPersonIdRoute = PersonsPersonIdRouteImport.update({
  id: '/persons/$personId',
  path: '/persons/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccidentsNewRoute = AccidentsNewRouteImport.update({
  id: '/accidents_/new',
  path: '/accidents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AccidentsNewVehicleRoute = AccidentsNewVehicleRouteImport.update({
  id: '/vehicle',
  path: '/vehicle',
  getParentRoute: () => AccidentsNewRoute,
} as any)
const AccidentsNewPersonRoute = AccidentsNewPersonRouteImport.update({
  id: '/person',
  path: '/person',
  getParentRoute: () => AccidentsNewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accidents': typeof AccidentsRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/statistics': typeof StatisticsRouteWithChildren
  '/user': typeof UserRoute
  '/user-applications': typeof UserApplicationsRoute
  '/accidents/new': typeof AccidentsNewRouteWithChildren
  '/persons/$personId': typeof PersonsPersonIdRoute
  '/register/medic': typeof RegisterMedicRoute
  '/register/police': typeof RegisterPoliceRoute
  '/statistics/main': typeof StatisticsMainRoute
  '/statistics/previous-quarter': typeof StatisticsPreviousQuarterRoute
  '/statistics/streets': typeof StatisticsStreetsRoute
  '/user/form': typeof UserFormRoute
  '/statistics/': typeof StatisticsIndexRoute
  '/accidents/new/person': typeof AccidentsNewPersonRoute
  '/accidents/new/vehicle': typeof AccidentsNewVehicleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accidents': typeof AccidentsRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/user': typeof UserRoute
  '/user-applications': typeof UserApplicationsRoute
  '/accidents/new': typeof AccidentsNewRouteWithChildren
  '/persons/$personId': typeof PersonsPersonIdRoute
  '/register/medic': typeof RegisterMedicRoute
  '/register/police': typeof RegisterPoliceRoute
  '/statistics/main': typeof StatisticsMainRoute
  '/statistics/previous-quarter': typeof StatisticsPreviousQuarterRoute
  '/statistics/streets': typeof StatisticsStreetsRoute
  '/user/form': typeof UserFormRoute
  '/statistics': typeof StatisticsIndexRoute
  '/accidents/new/person': typeof AccidentsNewPersonRoute
  '/accidents/new/vehicle': typeof AccidentsNewVehicleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accidents': typeof AccidentsRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/statistics': typeof StatisticsRouteWithChildren
  '/user': typeof UserRoute
  '/user-applications': typeof UserApplicationsRoute
  '/accidents_/new': typeof AccidentsNewRouteWithChildren
  '/persons/$personId': typeof PersonsPersonIdRoute
  '/register_/medic': typeof RegisterMedicRoute
  '/register_/police': typeof RegisterPoliceRoute
  '/statistics/main': typeof StatisticsMainRoute
  '/statistics/previous-quarter': typeof StatisticsPreviousQuarterRoute
  '/statistics/streets': typeof StatisticsStreetsRoute
  '/user_/form': typeof UserFormRoute
  '/statistics/': typeof StatisticsIndexRoute
  '/accidents_/new/person': typeof AccidentsNewPersonRoute
  '/accidents_/new/vehicle': typeof AccidentsNewVehicleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accidents'
    | '/admin'
    | '/login'
    | '/register'
    | '/report'
    | '/statistics'
    | '/user'
    | '/user-applications'
    | '/accidents/new'
    | '/persons/$personId'
    | '/register/medic'
    | '/register/police'
    | '/statistics/main'
    | '/statistics/previous-quarter'
    | '/statistics/streets'
    | '/user/form'
    | '/statistics/'
    | '/accidents/new/person'
    | '/accidents/new/vehicle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accidents'
    | '/admin'
    | '/login'
    | '/register'
    | '/report'
    | '/user'
    | '/user-applications'
    | '/accidents/new'
    | '/persons/$personId'
    | '/register/medic'
    | '/register/police'
    | '/statistics/main'
    | '/statistics/previous-quarter'
    | '/statistics/streets'
    | '/user/form'
    | '/statistics'
    | '/accidents/new/person'
    | '/accidents/new/vehicle'
  id:
    | '__root__'
    | '/'
    | '/accidents'
    | '/admin'
    | '/login'
    | '/register'
    | '/report'
    | '/statistics'
    | '/user'
    | '/user-applications'
    | '/accidents_/new'
    | '/persons/$personId'
    | '/register_/medic'
    | '/register_/police'
    | '/statistics/main'
    | '/statistics/previous-quarter'
    | '/statistics/streets'
    | '/user_/form'
    | '/statistics/'
    | '/accidents_/new/person'
    | '/accidents_/new/vehicle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccidentsRoute: typeof AccidentsRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ReportRoute: typeof ReportRoute
  StatisticsRoute: typeof StatisticsRouteWithChildren
  UserRoute: typeof UserRoute
  UserApplicationsRoute: typeof UserApplicationsRoute
  AccidentsNewRoute: typeof AccidentsNewRouteWithChildren
  PersonsPersonIdRoute: typeof PersonsPersonIdRoute
  RegisterMedicRoute: typeof RegisterMedicRoute
  RegisterPoliceRoute: typeof RegisterPoliceRoute
  UserFormRoute: typeof UserFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-applications': {
      id: '/user-applications'
      path: '/user-applications'
      fullPath: '/user-applications'
      preLoaderRoute: typeof UserApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accidents': {
      id: '/accidents'
      path: '/accidents'
      fullPath: '/accidents'
      preLoaderRoute: typeof AccidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics/': {
      id: '/statistics/'
      path: '/'
      fullPath: '/statistics/'
      preLoaderRoute: typeof StatisticsIndexRouteImport
      parentRoute: typeof StatisticsRoute
    }
    '/user_/form': {
      id: '/user_/form'
      path: '/user/form'
      fullPath: '/user/form'
      preLoaderRoute: typeof UserFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics/streets': {
      id: '/statistics/streets'
      path: '/streets'
      fullPath: '/statistics/streets'
      preLoaderRoute: typeof StatisticsStreetsRouteImport
      parentRoute: typeof StatisticsRoute
    }
    '/statistics/previous-quarter': {
      id: '/statistics/previous-quarter'
      path: '/previous-quarter'
      fullPath: '/statistics/previous-quarter'
      preLoaderRoute: typeof StatisticsPreviousQuarterRouteImport
      parentRoute: typeof StatisticsRoute
    }
    '/statistics/main': {
      id: '/statistics/main'
      path: '/main'
      fullPath: '/statistics/main'
      preLoaderRoute: typeof StatisticsMainRouteImport
      parentRoute: typeof StatisticsRoute
    }
    '/register_/police': {
      id: '/register_/police'
      path: '/register/police'
      fullPath: '/register/police'
      preLoaderRoute: typeof RegisterPoliceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register_/medic': {
      id: '/register_/medic'
      path: '/register/medic'
      fullPath: '/register/medic'
      preLoaderRoute: typeof RegisterMedicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons/$personId': {
      id: '/persons/$personId'
      path: '/persons/$personId'
      fullPath: '/persons/$personId'
      preLoaderRoute: typeof PersonsPersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accidents_/new': {
      id: '/accidents_/new'
      path: '/accidents/new'
      fullPath: '/accidents/new'
      preLoaderRoute: typeof AccidentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accidents_/new/vehicle': {
      id: '/accidents_/new/vehicle'
      path: '/vehicle'
      fullPath: '/accidents/new/vehicle'
      preLoaderRoute: typeof AccidentsNewVehicleRouteImport
      parentRoute: typeof AccidentsNewRoute
    }
    '/accidents_/new/person': {
      id: '/accidents_/new/person'
      path: '/person'
      fullPath: '/accidents/new/person'
      preLoaderRoute: typeof AccidentsNewPersonRouteImport
      parentRoute: typeof AccidentsNewRoute
    }
  }
}

interface StatisticsRouteChildren {
  StatisticsMainRoute: typeof StatisticsMainRoute
  StatisticsPreviousQuarterRoute: typeof StatisticsPreviousQuarterRoute
  StatisticsStreetsRoute: typeof StatisticsStreetsRoute
  StatisticsIndexRoute: typeof StatisticsIndexRoute
}

const StatisticsRouteChildren: StatisticsRouteChildren = {
  StatisticsMainRoute: StatisticsMainRoute,
  StatisticsPreviousQuarterRoute: StatisticsPreviousQuarterRoute,
  StatisticsStreetsRoute: StatisticsStreetsRoute,
  StatisticsIndexRoute: StatisticsIndexRoute,
}

const StatisticsRouteWithChildren = StatisticsRoute._addFileChildren(
  StatisticsRouteChildren,
)

interface AccidentsNewRouteChildren {
  AccidentsNewPersonRoute: typeof AccidentsNewPersonRoute
  AccidentsNewVehicleRoute: typeof AccidentsNewVehicleRoute
}

const AccidentsNewRouteChildren: AccidentsNewRouteChildren = {
  AccidentsNewPersonRoute: AccidentsNewPersonRoute,
  AccidentsNewVehicleRoute: AccidentsNewVehicleRoute,
}

const AccidentsNewRouteWithChildren = AccidentsNewRoute._addFileChildren(
  AccidentsNewRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccidentsRoute: AccidentsRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ReportRoute: ReportRoute,
  StatisticsRoute: StatisticsRouteWithChildren,
  UserRoute: UserRoute,
  UserApplicationsRoute: UserApplicationsRoute,
  AccidentsNewRoute: AccidentsNewRouteWithChildren,
  PersonsPersonIdRoute: PersonsPersonIdRoute,
  RegisterMedicRoute: RegisterMedicRoute,
  RegisterPoliceRoute: RegisterPoliceRoute,
  UserFormRoute: UserFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
