/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as UserApplicationsRouteImport } from './routes/user-applications'
import { Route as UserRouteImport } from './routes/user'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PersonsRouteImport } from './routes/persons'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccidentsRouteImport } from './routes/accidents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatisticsIndexRouteImport } from './routes/statistics/index'
import { Route as VehiclesNewRouteImport } from './routes/vehicles.new'
import { Route as VehiclesVehicleIdRouteImport } from './routes/vehicles/$vehicleId'
import { Route as UserFormRouteImport } from './routes/user_.form'
import { Route as StatisticsStreetsRouteImport } from './routes/statistics/streets'
import { Route as StatisticsPreviousQuarterRouteImport } from './routes/statistics/previous-quarter'
import { Route as RegisterPoliceRouteImport } from './routes/register_.police'
import { Route as RegisterMedicRouteImport } from './routes/register_.medic'
import { Route as PersonsNewRouteImport } from './routes/persons.new'
import { Route as AccidentsNewRouteImport } from './routes/accidents.new'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const UserApplicationsRoute = UserApplicationsRouteImport.update({
  id: '/user-applications',
  path: '/user-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsRoute = PersonsRouteImport.update({
  id: '/persons',
  path: '/persons',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccidentsRoute = AccidentsRouteImport.update({
  id: '/accidents',
  path: '/accidents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsIndexRoute = StatisticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StatisticsRoute,
} as any)
const VehiclesNewRoute = VehiclesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => VehiclesRoute,
} as any)
const VehiclesVehicleIdRoute = VehiclesVehicleIdRouteImport.update({
  id: '/$vehicleId',
  path: '/$vehicleId',
  getParentRoute: () => VehiclesRoute,
} as any)
const UserFormRoute = UserFormRouteImport.update({
  id: '/user_/form',
  path: '/user/form',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsStreetsRoute = StatisticsStreetsRouteImport.update({
  id: '/streets',
  path: '/streets',
  getParentRoute: () => StatisticsRoute,
} as any)
const StatisticsPreviousQuarterRoute =
  StatisticsPreviousQuarterRouteImport.update({
    id: '/previous-quarter',
    path: '/previous-quarter',
    getParentRoute: () => StatisticsRoute,
  } as any)
const RegisterPoliceRoute = RegisterPoliceRouteImport.update({
  id: '/register_/police',
  path: '/register/police',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterMedicRoute = RegisterMedicRouteImport.update({
  id: '/register_/medic',
  path: '/register/medic',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsNewRoute = PersonsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PersonsRoute,
} as any)
const AccidentsNewRoute = AccidentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AccidentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accidents': typeof AccidentsRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/persons': typeof PersonsRouteWithChildren
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/statistics': typeof StatisticsRouteWithChildren
  '/user': typeof UserRoute
  '/user-applications': typeof UserApplicationsRoute
  '/vehicles': typeof VehiclesRouteWithChildren
  '/accidents/new': typeof AccidentsNewRoute
  '/persons/new': typeof PersonsNewRoute
  '/register/medic': typeof RegisterMedicRoute
  '/register/police': typeof RegisterPoliceRoute
  '/statistics/previous-quarter': typeof StatisticsPreviousQuarterRoute
  '/statistics/streets': typeof StatisticsStreetsRoute
  '/user/form': typeof UserFormRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRoute
  '/vehicles/new': typeof VehiclesNewRoute
  '/statistics/': typeof StatisticsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accidents': typeof AccidentsRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/persons': typeof PersonsRouteWithChildren
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/user': typeof UserRoute
  '/user-applications': typeof UserApplicationsRoute
  '/vehicles': typeof VehiclesRouteWithChildren
  '/accidents/new': typeof AccidentsNewRoute
  '/persons/new': typeof PersonsNewRoute
  '/register/medic': typeof RegisterMedicRoute
  '/register/police': typeof RegisterPoliceRoute
  '/statistics/previous-quarter': typeof StatisticsPreviousQuarterRoute
  '/statistics/streets': typeof StatisticsStreetsRoute
  '/user/form': typeof UserFormRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRoute
  '/vehicles/new': typeof VehiclesNewRoute
  '/statistics': typeof StatisticsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accidents': typeof AccidentsRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/persons': typeof PersonsRouteWithChildren
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/statistics': typeof StatisticsRouteWithChildren
  '/user': typeof UserRoute
  '/user-applications': typeof UserApplicationsRoute
  '/vehicles': typeof VehiclesRouteWithChildren
  '/accidents/new': typeof AccidentsNewRoute
  '/persons/new': typeof PersonsNewRoute
  '/register_/medic': typeof RegisterMedicRoute
  '/register_/police': typeof RegisterPoliceRoute
  '/statistics/previous-quarter': typeof StatisticsPreviousQuarterRoute
  '/statistics/streets': typeof StatisticsStreetsRoute
  '/user_/form': typeof UserFormRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRoute
  '/vehicles/new': typeof VehiclesNewRoute
  '/statistics/': typeof StatisticsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accidents'
    | '/admin'
    | '/login'
    | '/persons'
    | '/register'
    | '/report'
    | '/statistics'
    | '/user'
    | '/user-applications'
    | '/vehicles'
    | '/accidents/new'
    | '/persons/new'
    | '/register/medic'
    | '/register/police'
    | '/statistics/previous-quarter'
    | '/statistics/streets'
    | '/user/form'
    | '/vehicles/$vehicleId'
    | '/vehicles/new'
    | '/statistics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accidents'
    | '/admin'
    | '/login'
    | '/persons'
    | '/register'
    | '/report'
    | '/user'
    | '/user-applications'
    | '/vehicles'
    | '/accidents/new'
    | '/persons/new'
    | '/register/medic'
    | '/register/police'
    | '/statistics/previous-quarter'
    | '/statistics/streets'
    | '/user/form'
    | '/vehicles/$vehicleId'
    | '/vehicles/new'
    | '/statistics'
  id:
    | '__root__'
    | '/'
    | '/accidents'
    | '/admin'
    | '/login'
    | '/persons'
    | '/register'
    | '/report'
    | '/statistics'
    | '/user'
    | '/user-applications'
    | '/vehicles'
    | '/accidents/new'
    | '/persons/new'
    | '/register_/medic'
    | '/register_/police'
    | '/statistics/previous-quarter'
    | '/statistics/streets'
    | '/user_/form'
    | '/vehicles/$vehicleId'
    | '/vehicles/new'
    | '/statistics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccidentsRoute: typeof AccidentsRouteWithChildren
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  PersonsRoute: typeof PersonsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ReportRoute: typeof ReportRoute
  StatisticsRoute: typeof StatisticsRouteWithChildren
  UserRoute: typeof UserRoute
  UserApplicationsRoute: typeof UserApplicationsRoute
  VehiclesRoute: typeof VehiclesRouteWithChildren
  RegisterMedicRoute: typeof RegisterMedicRoute
  RegisterPoliceRoute: typeof RegisterPoliceRoute
  UserFormRoute: typeof UserFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-applications': {
      id: '/user-applications'
      path: '/user-applications'
      fullPath: '/user-applications'
      preLoaderRoute: typeof UserApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons': {
      id: '/persons'
      path: '/persons'
      fullPath: '/persons'
      preLoaderRoute: typeof PersonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accidents': {
      id: '/accidents'
      path: '/accidents'
      fullPath: '/accidents'
      preLoaderRoute: typeof AccidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics/': {
      id: '/statistics/'
      path: '/'
      fullPath: '/statistics/'
      preLoaderRoute: typeof StatisticsIndexRouteImport
      parentRoute: typeof StatisticsRoute
    }
    '/vehicles/new': {
      id: '/vehicles/new'
      path: '/new'
      fullPath: '/vehicles/new'
      preLoaderRoute: typeof VehiclesNewRouteImport
      parentRoute: typeof VehiclesRoute
    }
    '/vehicles/$vehicleId': {
      id: '/vehicles/$vehicleId'
      path: '/$vehicleId'
      fullPath: '/vehicles/$vehicleId'
      preLoaderRoute: typeof VehiclesVehicleIdRouteImport
      parentRoute: typeof VehiclesRoute
    }
    '/user_/form': {
      id: '/user_/form'
      path: '/user/form'
      fullPath: '/user/form'
      preLoaderRoute: typeof UserFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics/streets': {
      id: '/statistics/streets'
      path: '/streets'
      fullPath: '/statistics/streets'
      preLoaderRoute: typeof StatisticsStreetsRouteImport
      parentRoute: typeof StatisticsRoute
    }
    '/statistics/previous-quarter': {
      id: '/statistics/previous-quarter'
      path: '/previous-quarter'
      fullPath: '/statistics/previous-quarter'
      preLoaderRoute: typeof StatisticsPreviousQuarterRouteImport
      parentRoute: typeof StatisticsRoute
    }
    '/register_/police': {
      id: '/register_/police'
      path: '/register/police'
      fullPath: '/register/police'
      preLoaderRoute: typeof RegisterPoliceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register_/medic': {
      id: '/register_/medic'
      path: '/register/medic'
      fullPath: '/register/medic'
      preLoaderRoute: typeof RegisterMedicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons/new': {
      id: '/persons/new'
      path: '/new'
      fullPath: '/persons/new'
      preLoaderRoute: typeof PersonsNewRouteImport
      parentRoute: typeof PersonsRoute
    }
    '/accidents/new': {
      id: '/accidents/new'
      path: '/new'
      fullPath: '/accidents/new'
      preLoaderRoute: typeof AccidentsNewRouteImport
      parentRoute: typeof AccidentsRoute
    }
  }
}

interface AccidentsRouteChildren {
  AccidentsNewRoute: typeof AccidentsNewRoute
}

const AccidentsRouteChildren: AccidentsRouteChildren = {
  AccidentsNewRoute: AccidentsNewRoute,
}

const AccidentsRouteWithChildren = AccidentsRoute._addFileChildren(
  AccidentsRouteChildren,
)

interface PersonsRouteChildren {
  PersonsNewRoute: typeof PersonsNewRoute
}

const PersonsRouteChildren: PersonsRouteChildren = {
  PersonsNewRoute: PersonsNewRoute,
}

const PersonsRouteWithChildren =
  PersonsRoute._addFileChildren(PersonsRouteChildren)

interface StatisticsRouteChildren {
  StatisticsPreviousQuarterRoute: typeof StatisticsPreviousQuarterRoute
  StatisticsStreetsRoute: typeof StatisticsStreetsRoute
  StatisticsIndexRoute: typeof StatisticsIndexRoute
}

const StatisticsRouteChildren: StatisticsRouteChildren = {
  StatisticsPreviousQuarterRoute: StatisticsPreviousQuarterRoute,
  StatisticsStreetsRoute: StatisticsStreetsRoute,
  StatisticsIndexRoute: StatisticsIndexRoute,
}

const StatisticsRouteWithChildren = StatisticsRoute._addFileChildren(
  StatisticsRouteChildren,
)

interface VehiclesRouteChildren {
  VehiclesVehicleIdRoute: typeof VehiclesVehicleIdRoute
  VehiclesNewRoute: typeof VehiclesNewRoute
}

const VehiclesRouteChildren: VehiclesRouteChildren = {
  VehiclesVehicleIdRoute: VehiclesVehicleIdRoute,
  VehiclesNewRoute: VehiclesNewRoute,
}

const VehiclesRouteWithChildren = VehiclesRoute._addFileChildren(
  VehiclesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccidentsRoute: AccidentsRouteWithChildren,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  PersonsRoute: PersonsRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ReportRoute: ReportRoute,
  StatisticsRoute: StatisticsRouteWithChildren,
  UserRoute: UserRoute,
  UserApplicationsRoute: UserApplicationsRoute,
  VehiclesRoute: VehiclesRouteWithChildren,
  RegisterMedicRoute: RegisterMedicRoute,
  RegisterPoliceRoute: RegisterPoliceRoute,
  UserFormRoute: UserFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
