/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as UserRouteImport } from './routes/user'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PersonsRouteImport } from './routes/persons'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccidentsRouteImport } from './routes/accidents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehiclesNewRouteImport } from './routes/vehicles.new'
import { Route as VehiclesVehicleIdRouteImport } from './routes/vehicles/$vehicleId'
import { Route as UserFormRouteImport } from './routes/user_.form'
import { Route as PersonsNewRouteImport } from './routes/persons.new'
import { Route as AccidentsNewRouteImport } from './routes/accidents.new'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsRoute = PersonsRouteImport.update({
  id: '/persons',
  path: '/persons',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccidentsRoute = AccidentsRouteImport.update({
  id: '/accidents',
  path: '/accidents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesNewRoute = VehiclesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => VehiclesRoute,
} as any)
const VehiclesVehicleIdRoute = VehiclesVehicleIdRouteImport.update({
  id: '/$vehicleId',
  path: '/$vehicleId',
  getParentRoute: () => VehiclesRoute,
} as any)
const UserFormRoute = UserFormRouteImport.update({
  id: '/user_/form',
  path: '/user/form',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsNewRoute = PersonsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PersonsRoute,
} as any)
const AccidentsNewRoute = AccidentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AccidentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accidents': typeof AccidentsRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/persons': typeof PersonsRouteWithChildren
  '/register': typeof RegisterRoute
  '/user': typeof UserRoute
  '/vehicles': typeof VehiclesRouteWithChildren
  '/accidents/new': typeof AccidentsNewRoute
  '/persons/new': typeof PersonsNewRoute
  '/user/form': typeof UserFormRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRoute
  '/vehicles/new': typeof VehiclesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accidents': typeof AccidentsRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/persons': typeof PersonsRouteWithChildren
  '/register': typeof RegisterRoute
  '/user': typeof UserRoute
  '/vehicles': typeof VehiclesRouteWithChildren
  '/accidents/new': typeof AccidentsNewRoute
  '/persons/new': typeof PersonsNewRoute
  '/user/form': typeof UserFormRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRoute
  '/vehicles/new': typeof VehiclesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accidents': typeof AccidentsRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/persons': typeof PersonsRouteWithChildren
  '/register': typeof RegisterRoute
  '/user': typeof UserRoute
  '/vehicles': typeof VehiclesRouteWithChildren
  '/accidents/new': typeof AccidentsNewRoute
  '/persons/new': typeof PersonsNewRoute
  '/user_/form': typeof UserFormRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRoute
  '/vehicles/new': typeof VehiclesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accidents'
    | '/admin'
    | '/login'
    | '/persons'
    | '/register'
    | '/user'
    | '/vehicles'
    | '/accidents/new'
    | '/persons/new'
    | '/user/form'
    | '/vehicles/$vehicleId'
    | '/vehicles/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accidents'
    | '/admin'
    | '/login'
    | '/persons'
    | '/register'
    | '/user'
    | '/vehicles'
    | '/accidents/new'
    | '/persons/new'
    | '/user/form'
    | '/vehicles/$vehicleId'
    | '/vehicles/new'
  id:
    | '__root__'
    | '/'
    | '/accidents'
    | '/admin'
    | '/login'
    | '/persons'
    | '/register'
    | '/user'
    | '/vehicles'
    | '/accidents/new'
    | '/persons/new'
    | '/user_/form'
    | '/vehicles/$vehicleId'
    | '/vehicles/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccidentsRoute: typeof AccidentsRouteWithChildren
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  PersonsRoute: typeof PersonsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  UserRoute: typeof UserRoute
  VehiclesRoute: typeof VehiclesRouteWithChildren
  UserFormRoute: typeof UserFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons': {
      id: '/persons'
      path: '/persons'
      fullPath: '/persons'
      preLoaderRoute: typeof PersonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accidents': {
      id: '/accidents'
      path: '/accidents'
      fullPath: '/accidents'
      preLoaderRoute: typeof AccidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/new': {
      id: '/vehicles/new'
      path: '/new'
      fullPath: '/vehicles/new'
      preLoaderRoute: typeof VehiclesNewRouteImport
      parentRoute: typeof VehiclesRoute
    }
    '/vehicles/$vehicleId': {
      id: '/vehicles/$vehicleId'
      path: '/$vehicleId'
      fullPath: '/vehicles/$vehicleId'
      preLoaderRoute: typeof VehiclesVehicleIdRouteImport
      parentRoute: typeof VehiclesRoute
    }
    '/user_/form': {
      id: '/user_/form'
      path: '/user/form'
      fullPath: '/user/form'
      preLoaderRoute: typeof UserFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons/new': {
      id: '/persons/new'
      path: '/new'
      fullPath: '/persons/new'
      preLoaderRoute: typeof PersonsNewRouteImport
      parentRoute: typeof PersonsRoute
    }
    '/accidents/new': {
      id: '/accidents/new'
      path: '/new'
      fullPath: '/accidents/new'
      preLoaderRoute: typeof AccidentsNewRouteImport
      parentRoute: typeof AccidentsRoute
    }
  }
}

interface AccidentsRouteChildren {
  AccidentsNewRoute: typeof AccidentsNewRoute
}

const AccidentsRouteChildren: AccidentsRouteChildren = {
  AccidentsNewRoute: AccidentsNewRoute,
}

const AccidentsRouteWithChildren = AccidentsRoute._addFileChildren(
  AccidentsRouteChildren,
)

interface PersonsRouteChildren {
  PersonsNewRoute: typeof PersonsNewRoute
}

const PersonsRouteChildren: PersonsRouteChildren = {
  PersonsNewRoute: PersonsNewRoute,
}

const PersonsRouteWithChildren =
  PersonsRoute._addFileChildren(PersonsRouteChildren)

interface VehiclesRouteChildren {
  VehiclesVehicleIdRoute: typeof VehiclesVehicleIdRoute
  VehiclesNewRoute: typeof VehiclesNewRoute
}

const VehiclesRouteChildren: VehiclesRouteChildren = {
  VehiclesVehicleIdRoute: VehiclesVehicleIdRoute,
  VehiclesNewRoute: VehiclesNewRoute,
}

const VehiclesRouteWithChildren = VehiclesRoute._addFileChildren(
  VehiclesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccidentsRoute: AccidentsRouteWithChildren,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  PersonsRoute: PersonsRouteWithChildren,
  RegisterRoute: RegisterRoute,
  UserRoute: UserRoute,
  VehiclesRoute: VehiclesRouteWithChildren,
  UserFormRoute: UserFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
